image: gitpod/workspace-elixir:2022-04-01-12-31-37

# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: |
      sudo apt-get update -y
      sudo apt-get install erlang -y
      chmod +x ./install.sh
  - command: ./install.sh




# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 4000
    onOpen: open-preview
