image: gitpod/workspace-elixir:2022-11-15-17-00-18

# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: chmod +x ./install.sh
  - command: ./install.sh




# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 4000
    onOpen: open-preview
